# Generated by Django 3.0.3 on 2020-02-17 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
