# Generated by Django 3.0.3 on 2020-02-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20200217_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='technology'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='Technology', max_length=50),
        ),
    ]
