language: python

python:
  - 3.6

env:
  - DJANGO=3.0.3
  - SECRET_KEY=$SECRET_KEY
  - DEBUG_VALUE=$DEBUG_VALUE

before_install:
  - export DJANGO_SETTINGS_MODULE=blog.settings

install:
  - pip install -r requirements.txt

script:
  - python manage.py test
